import { describe, expect, it } from "vitest";
import { attachExactTokenProvenance, findExactTokenProvenance, spatialTokensFromNormalizedPage, validateIndependentRelation, type ClinicalEvidenceItem, type SpatialToken } from "@/lib/clinical-evidence";
import { buildClinicalTrustCandidate, clinicalEvidenceProvenanceLevel } from "@/lib/verification-trust";

const box={normalizedVertices:[{x:.1,y:.1},{x:.2,y:.1},{x:.2,y:.2},{x:.1,y:.2}]};
const token=(id:string,text:string,index:number):SpatialToken=>({id,text,page:1,coordinates:box,confidence:.99,textAnchor:{start:index*10,end:index*10+text.length}});
const tokens=[token("t1","Left",0),token("t2","breast",1),token("t3","mass",2),token("t4","12",3),token("t5","mm",4)];
const fact=(text="Left breast mass 12 mm"):ClinicalEvidenceItem=>({evidenceId:"f1",caseId:"c",sourceDocumentId:"d",documentType:"RADIOLOGY",evidenceType:"MEASUREMENT",originalText:text,normalizedText:null,numericValue:12,codedValue:null,laterality:"LEFT",anatomicalSite:"breast",eventDate:null,dateKind:null,sourcePage:1,sourceCoordinates:box,extractionConfidence:.99,layoutConfidence:.99,verificationStatus:"NEEDS_REVIEW",normalizationStatus:"UNRESOLVED",providerVersion:"p",parserVersion:"v",canonicalLabFactId:null,caseEventId:null});

describe("P3/P4 clinical provenance",()=>{
  it("creates P3 only for one exact contiguous token sequence",()=>{const result=findExactTokenProvenance("Left breast mass 12 mm",1,tokens);expect(result.status).toBe("P3");if(result.status==="P3") expect(result.provenance).toMatchObject({level:"P3",tokenIds:["t1","t2","t3","t4","t5"],documentTextSpan:{start:0,end:42}});});
  it("keeps ambiguous repeated source text at P2",()=>{expect(findExactTokenProvenance("Left breast",1,[...tokens,token("t6","Left",5),token("t7","breast",6)])).toEqual({status:"P2",reason:"AMBIGUOUS_TOKEN_MATCH"});});
  it("keeps missing and non-contiguous evidence at P2",()=>{expect(findExactTokenProvenance("Left mass",1,tokens)).toEqual({status:"P2",reason:"NO_EXACT_TOKEN_MATCH"});});
  it("does not promote malformed token geometry",()=>{expect(findExactTokenProvenance("Left",1,[{...tokens[0],coordinates:{}}])).toEqual({status:"P2",reason:"INVALID_TOKEN_GEOMETRY"});});
  it("attaches provenance without changing verification state or source",()=>{const output=attachExactTokenProvenance([fact()],tokens)[0];expect(output).toMatchObject({verificationStatus:"NEEDS_REVIEW",originalText:"Left breast mass 12 mm",tokenProvenance:{level:"P3"}});});
  it("requires an independent passing relation check for P4",()=>{const result=findExactTokenProvenance("Left breast mass 12 mm",1,tokens);if(result.status!=="P3") throw new Error("fixture");expect(validateIndependentRelation(result.provenance,{method:"same parser",independentSignal:false,passed:true}).level).toBe("P3");expect(validateIndependentRelation(result.provenance,{method:"spatial reevaluation",independentSignal:true,passed:true}).level).toBe("P4");});
  it("maps provider-neutral normalized anchors into spatial tokens",()=>{const mapped=spatialTokensFromNormalizedPage({pageNumber:1,detectedLanguages:[],qualityDefects:[],blocks:[],paragraphs:[],lines:[],tables:[],tokens:[{id:"p1-token-0",text:"Left",textAnchor:{start:0,end:4},confidence:.99,boundingPoly:box}]});expect(mapped[0]).toMatchObject({id:"p1-token-0",page:1,textAnchor:{start:0,end:4}});});
  it("maps P3 into trust input without manufacturing other dimensions",()=>{const attached=attachExactTokenProvenance([fact()],tokens)[0];expect(clinicalEvidenceProvenanceLevel(attached)).toBe("P3");const candidate=buildClinicalTrustCandidate(attached,{evidenceClass:"RADIOLOGY_MEASUREMENT",fieldParseConfidence:null,normalizationConfidence:null,documentQualityConfidence:null,contextAssociationConfidence:null,deterministicChecks:[],crossChecks:[],normalizationRequired:false,competingCandidateCount:1,sourceAmbiguous:false});expect(candidate).toMatchObject({provenanceLevel:"P3",confidences:{fieldParse:null,sourceProvenance:null,documentQuality:null}});});
});
