import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { EVIDENCE_CLASSES, TRUST_POLICY_VERSION, TRUST_REASON_CODES, evaluateShadow, evaluateTrustCandidate, type CheckResult, type EvidenceClass, type TrustCandidate } from "@/lib/verification-trust";

const checks: CheckResult[]=["NUMERIC_PARSE","UNIT_VALUE_SEPARATION","REFERENCE_VALUE_SEPARATION","LABEL_VALUE_ASSOCIATION","DATE_EVENT_ASSOCIATION","LATERALITY_SITE_ASSOCIATION","IDEMPOTENCY","SOURCE_EXISTS","SCHEMA_CONSTRAINTS","LAYOUT_CONTRADICTION"].map(name=>({name:name as CheckResult["name"],passed:true}));
const candidate=(overrides:Partial<TrustCandidate>={}):TrustCandidate=>({factId:"fact-1",evidenceClass:"LAB_NUMERIC",inputVerificationState:"NEEDS_REVIEW",confidences:{ocrText:.995,layout:.995,fieldParse:.995,sourceProvenance:.995,normalization:.995,crossCheck:.995,documentQuality:.99,contextAssociation:.995},provenanceLevel:"P4",deterministicChecks:checks,crossChecks:[{method:"INDEPENDENT_PARSER",independentSignal:true,passed:true}],normalizationRequired:true,competingCandidateCount:1,sourceAmbiguous:false,...overrides});

describe("verification trust gates",()=>{
  it("defines a versioned declarative policy for every evidence class",()=>{expect(TRUST_POLICY_VERSION).toBe("phase-2.7-shadow-v1");expect(EVIDENCE_CLASSES).toHaveLength(12);expect(TRUST_REASON_CODES).toContain("MISSING_TOKEN_PROVENANCE");});
  it("allows a fully supported shadow candidate without mutating stored state",()=>{const result=evaluateShadow(candidate(),"fixed");expect(result.storedVerificationState).toBe("NEEDS_REVIEW");expect(result.decision).toMatchObject({wouldAutoVerify:true,finalVerificationState:"VERIFIED",shadowDecision:true,policyVersion:TRUST_POLICY_VERSION});});
  it("blocks a missing required signal",()=>{const c=candidate({confidences:{...candidate().confidences,fieldParse:null}});expect(evaluateTrustCandidate(c,"fixed")).toMatchObject({wouldAutoVerify:false,finalVerificationState:"NEEDS_REVIEW"});});
  it("separately reports low OCR and low layout",()=>{const c=candidate({confidences:{...candidate().confidences,ocrText:.7,layout:.7}});expect(evaluateTrustCandidate(c,"fixed").decisionReasonCodes).toEqual(expect.arrayContaining(["LOW_OCR_CONFIDENCE","LOW_LAYOUT_CONFIDENCE"]));});
  it("does not let good OCR compensate for bad layout",()=>{const c=candidate({confidences:{...candidate().confidences,ocrText:1,layout:.6}});expect(evaluateTrustCandidate(c,"fixed")).toMatchObject({wouldAutoVerify:false,decisionReasonCodes:expect.arrayContaining(["LOW_LAYOUT_CONFIDENCE"])});});
  it("keeps a good source fact unresolved when normalization is missing",()=>{const c=candidate({confidences:{...candidate().confidences,normalization:null}});expect(evaluateTrustCandidate(c,"fixed").decisionReasonCodes).toContain("NORMALIZATION_UNRESOLVED");});
  it("blocks second-pass disagreement",()=>{const c=candidate({crossChecks:[{method:"INDEPENDENT_PARSER",independentSignal:true,passed:false}]});expect(evaluateTrustCandidate(c,"fixed").decisionReasonCodes).toContain("SECOND_PASS_DISAGREEMENT");});
  it("does not count a circular check as independent",()=>{const c=candidate({crossChecks:[{method:"INDEPENDENT_PARSER",independentSignal:false,passed:true}]});expect(evaluateTrustCandidate(c,"fixed")).toMatchObject({wouldAutoVerify:false,decisionReasonCodes:expect.arrayContaining(["POLICY_REQUIREMENT_NOT_MET"])});});
  it("requires token provenance and detects competing candidates",()=>{const c=candidate({provenanceLevel:"P2",competingCandidateCount:2});expect(evaluateTrustCandidate(c,"fixed").decisionReasonCodes).toEqual(expect.arrayContaining(["MISSING_TOKEN_PROVENANCE","AMBIGUOUS_ROW_ASSOCIATION"]));});
  it("routes ambiguous narrative source to SOURCE_ONLY",()=>{const c=candidate({evidenceClass:"NARRATIVE_SOURCE_FACT",sourceAmbiguous:true,normalizationRequired:false});expect(evaluateTrustCandidate(c,"fixed").finalVerificationState).toBe("SOURCE_ONLY");});
  it("produces immutable snapshots and version-distinct decision IDs",()=>{const c=candidate(), first=evaluateTrustCandidate(c,"one"),second=evaluateTrustCandidate(c,"two");c.confidences.ocrText=0;expect(first.confidenceDimensions.ocrText).toBe(.995);expect(first.decisionId).not.toBe(second.decisionId);});
  it("keeps repository persistence shadow-only, append-only and inaccessible to clients",()=>{const sql=readFileSync("supabase/migrations/20260903182611_verification_trust_shadow_layer.sql","utf8");expect(sql).toContain("shadow_only boolean not null default true check (shadow_only)");expect(sql).toContain("Clinical trust history is append-only");expect(sql).toContain("revoke all on public.verification_policy_versions");expect(sql).not.toMatch(/alter table public\.(?:clinical_evidence_items|canonical_lab_facts)/);});
  it.each<EvidenceClass>([...EVIDENCE_CLASSES])("evaluates policy class %s",evidenceClass=>{expect(evaluateTrustCandidate(candidate({evidenceClass,normalizationRequired:false}),"fixed").evidenceClass).toBe(evidenceClass);});
});
